### ISSUE TITLE
Can't build a version of the Browser?

### ISSUE THREAD

**Issue by M-Saadawy** [MahApps/IconPacks.Browser#37]
Thank you so much!

I can't seem to be able to build a version of the browser or find a downloadable one. 

Can anyone please help?

Thanks!

**Comment by M-Saadawy** [comment]
Can't even find the browser here to set it as the starting point.
![Screenshot 2024-07-12 225936](https://github.com/user-attachments/assets/21aec82c-4591-4d01-85b0-42634f18850c)

**Comment by M-Saadawy** [comment]
Turns out there's a version of the browser here:
https://ghost1372.github.io/handycontrol/native_controls/button/

**Comment by punker76** [comment]
I don’t know what the problem here is, but the latest version can be downloaded here: https://github.com/MahApps/IconPacks.Browser/releases
