### ISSUE TITLE
.exe for download

### ISSUE THREAD

**Issue by TamaraMayer** [MahApps/IconPacks.Browser#9]
Hey guys.
I'd really love to use your IconPack and therefore the IconPack Browser too. 
Unfortunalty i am not able to run the code without putting a lot of time into it with installing the right dependencies. It would be really awesome if you could just make a .exe build of the IconPack Browser available.

**Comment by MartinJSoles** [comment]
I'm in agreement. There used to be an exe available. I can't remember where it was, though. I've cloned the source but unable to get it to compile in VS 2022.
